#!/usr/bin/env python3
"""Compile the checked-in MNK interval policy into native dispatch code."""

import argparse
import hashlib
import json
from pathlib import Path


def generate(source):
    policy = json.loads(source.read_text())
    assert policy["version"] == 2

    def expression(config):
        if isinstance(config, list):
            assert len(config) == 4 and all(isinstance(v, int) for v in config)
            return "LaunchConfig{" + ", ".join(map(str, config)) + "}"
        assert config["axis"] in ("m", "n", "k")
        return f"({config['axis']} <= {int(config['upper'])} ? {expression(config['le'])} : {expression(config['gt'])})"

    lines = [
        "#pragma once",
        "// Generated by scripts/generate_mxfp8_dispatch.py; edit the JSON policy.",
        "namespace mxfp8_runtime {",
        f'inline constexpr char policy_sha256[] = "{hashlib.sha256(source.read_bytes()).hexdigest()}";',
        "inline LaunchConfig select_config(int64_t m, int64_t n, int64_t k) {",
        '  TORCH_CHECK(m > 0 && n > 0 && k > 0, "MXFP8 dimensions must be positive");',
    ]
    for r in policy["regions"]:
        terms = [
            f"{axis} <= {r[axis+'_max']}"
            for axis in ("n", "k")
            if r[axis + "_max"] is not None
        ]
        assert len(r["configs"]) == len(policy["m_bounds"])
        lines.append("  if (" + " && ".join(terms) + ") {")
        for upper, cfg in zip(policy["m_bounds"], r["configs"]):
            lines.append(f"    if (m <= {upper}) return {expression(cfg)};")
        lines.append("    return {79, 1, 1, 0};")
        lines.append("  }")
    lines += [
        "  if (m > 2048) return {79, 1, 1, 0};",
        "  if (k > 3072) {",
        "    int64_t tactic = m <= 8 ? 12 : m <= 32 ? 13 : m <= 64 ? 14 : m <= 256 ? 15 : 16;",
        "    int64_t splits = m <= 128 ? (k >= 8192 ? 4 : 2) : 1;",
        "    return {tactic, splits, 1, 0};",
        "  }",
        "  return {m <= 8 ? 0 : m <= 16 ? 2 : m <= 32 ? 4 : m <= 64 ? 7 : 9, 1, 1, 0};",
        "}",
        "} // namespace mxfp8_runtime",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("source", type=Path)
    p.add_argument("output", type=Path)
    a = p.parse_args()
    text = generate(a.source)
    a.output.parent.mkdir(parents=True, exist_ok=True)
    if not a.output.exists() or a.output.read_text() != text:
        a.output.write_text(text)
